inherit_from:
  - vendor/hound/config/style_guides/ruby.yml
  - .rubocop_todo.yml

# Files you want to exclude
AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - tmp/aruba/Guardfile
    - tmp/aruba/Gemfile
    - Guardfile
    - config/Guardfile

# TODO: put your overrides here:
